# Generated by Django 2.1.7 on 2019-03-28 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ranges',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_age', models.IntegerField(default=0)),
                ('max_age', models.IntegerField(default=0)),
                ('min_normal_pulse', models.IntegerField(default=0)),
                ('max_normal_pulse', models.IntegerField(default=0)),
                ('min_limit', models.IntegerField(default=0)),
                ('max_limit', models.IntegerField(default=0)),
                ('gender', models.CharField(blank=True, max_length=1)),
            ],
        ),
    ]
