# Generated by Django 2.1.7 on 2019-03-24 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('measurements', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ranges',
            name='max_age',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ranges',
            name='max_limit',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ranges',
            name='max_normal_pulse',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ranges',
            name='min_age',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ranges',
            name='min_limit',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ranges',
            name='min_normal_pulse',
            field=models.IntegerField(default=0),
        ),
    ]
